### "/"
GET http://localhost:8000 HTTP/1.1

### "/register"
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "nickName": "Jhon",
    "email": "dave@example.com",
    "password": "password"
}

### test login api use nickname and password
### "/login"
POST http://localhost:8000/login?t=nickname HTTP/1.1
Content-Type: application/json

{
    "nickname": "Jhon",
    "password": "password"
}

### test login api use email and password
POST http://localhost:8000/login?t=email HTTP/1.1
Content-Type: application/json

{
    "email": "dave@example.com",
    "password": "password"
}

### test token is valid
### "/restricted"
GET http://localhost:8000/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAxNDk1NDUsImlkIjoxLCJuaWNrbmFtZSI6IkRhdmUifQ.QI3Tmf_-5YIyaeP6-6rm_20yWV7etvuASkg591GFUFo

###
GET http://localhost:8000/check HTTP/1.1

### /playlist
### not login
GET http://localhost:8000/playlist HTTP/1.1

### /playlist
### Invalid or expired JWT
GET http://localhost:8000/playlist HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAxNDk1NDUsImlkIjoxLCJuaWNrbmFtZSI6IkRhdmUifQ.QI3Tmf_-5YIyaeP6-6rm_20yWV7etvuASkg591GFUFo

### /playlist
### valid token
GET http://localhost:8000/playlist HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODI1OTg1MjYsImlkIjoxLCJuaWNrbmFtZSI6IkRhdmUifQ.xO_G5JIhL8zyor5f6N_MA2iap3t-396Vm_W_IVjyZDU

### /playlist
### create playlist
### no token
POST http://localhost:8000/playlist HTTP/1.1
Content-Type: application/json

{
    "name": "playlist1",
}

### /playlist
### create playlist
### valid token
POST http://localhost:8000/playlist HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODI1OTg1MjYsImlkIjoxLCJuaWNrbmFtZSI6IkRhdmUifQ.xO_G5JIhL8zyor5f6N_MA2iap3t-396Vm_W_IVjyZDU
Content-Type: application/json

{
    "name": "playlist1"
}

### /playlist
### delete playlist
### no token
DELETE http://localhost:8000/playlist/2 HTTP/1.1

### /playlist
### delete playlist
### valid token
DELETE http://localhost:8000/playlist/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODI1OTg1MjYsImlkIjoxLCJuaWNrbmFtZSI6IkRhdmUifQ.xO_G5JIhL8zyor5f6N_MA2iap3t-396Vm_W_IVjyZDU